name: rpi2
on: workflow_dispatch


jobs:
  packages:
    uses: pikvm/packages/.github/workflows/packages.yml@master
    with:
      BOARD: rpi2
    secrets:
      DEPLOY_KEY: "${{secrets.DEPLOY_KEY}}"
